baseURL = "https://deveshnathjha.github.io/"
languageCode = "en-us"
title = "Devesh Nath Jha"
theme = "PaperMod"

[params]
  author = "Devesh Nath Jha"
  description = "Engineering, AI, and Systems Architecture"
  ShowReadingTime = true
  ShowToc = true

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jha-devesh/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:deveshjnv2002@gmail.com"

